/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.favoriteteam.service;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType PlayersCard.
 *
 * @since 2021-08-24
 */
@PrimaryKeys({"id"})
public final class PlayersCard extends CloudDBZoneObject {
    private Integer id;

    private String power;

    private String position;

    private String country;

    private String team;

    private String playerphoto;

    private String name;

    private String pace;

    private String shoot;

    private String pass;

    private String dribling;

    private String defence;

    private String phy;

    private Integer playerid;

    public PlayersCard() {
        super(PlayersCard.class);
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setPower(String power) {
        this.power = power;
    }

    public String getPower() {
        return power;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getPosition() {
        return position;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCountry() {
        return country;
    }

    public void setTeam(String team) {
        this.team = team;
    }

    public String getTeam() {
        return team;
    }

    public void setPlayerphoto(String playerphoto) {
        this.playerphoto = playerphoto;
    }

    public String getPlayerphoto() {
        return playerphoto;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setPace(String pace) {
        this.pace = pace;
    }

    public String getPace() {
        return pace;
    }

    public void setShoot(String shoot) {
        this.shoot = shoot;
    }

    public String getShoot() {
        return shoot;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getPass() {
        return pass;
    }

    public void setDribling(String dribling) {
        this.dribling = dribling;
    }

    public String getDribling() {
        return dribling;
    }

    public void setDefence(String defence) {
        this.defence = defence;
    }

    public String getDefence() {
        return defence;
    }

    public void setPhy(String phy) {
        this.phy = phy;
    }

    public String getPhy() {
        return phy;
    }

    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    public Integer getPlayerid() {
        return playerid;
    }

}
